id: P2BE648E4
initial_creation_type: ocr
source_metadata:
  volumes:
    150812bf73a04886b1f77a3117cfb449:
      base_file: v076.txt
      image_group_id: I1PD95921
      title: དོན་གསང་བ་རྣམ་པར་ཕྱེ་བ་བསྡུས་ཏེ་བཤད་པ།
      total_pages: 1774
      volume_number: 76
